### ISSUE TITLE
Using 360 degree cubemap faces as input with two different orientation to get overlap

### ISSUE THREAD

**Issue by PHOENIXFURY007** [paulengstler/invisible-stitch#13]
Is it possible to use 2 images with overlap, instead of just the text?
As shown in the demo image, if I use I0 and I1 to generate a scene and then introduce I2 to continue from where I2 finished such that consecutive images have some overlap, so will it be possible to use just images without any text ?

**Comment by paulengstler** [comment]
I'm not sure I fully understand what you are looking to do. If you are looking to stitch existing 2D images together, I would look into panorama stitching. If you are looking to eliminate the need for text conditioning, you can either set the guidance scale to `1.0` and use any text prompt, or replace the image generation model. If that isn't what you were referring to, please feel free to reach out again.
