### ISSUE TITLE
Ran into issues with environment setup

### ISSUE THREAD

**Issue by PHOENIXFURY007** [paulengstler/invisible-stitch#2]
I was initially using the older version and now downloaded it recursively as mentioned in #1 

But I am still running into this error. 
(base) [phoenix@pleiades1 invisible-stitch]$ conda env create -n invisible_stitch --file environment.yml
Collecting package metadata (repodata.json): \ WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
done
Solving environment: failed

ResolvePackageNotFound: 
  - matplotlib=3.7.5
  - matplotlib-base=3.7.5

**Comment by paulengstler** [comment]
Fixed with baa7ab2. My apologies, for some reason I missed updating these! Please let me know if you run into any other issues!

**Comment by PHOENIXFURY007** [comment]
Thanks for the answer. I was finally able to finish up the environment setup.
