### ISSUE TITLE
Environment setup for Mac . How to set it up without using CUDA as its not available on mac

### ISSUE THREAD

**Issue by PHOENIXFURY007** [paulengstler/invisible-stitch#3]
(base) phoenix@Gauravs-MacBook-Air invisible-stitch % conda env create -n invisible_stitch --file environment.yml
Channels:
 - pytorch
 - nvidia
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed
Channels:
 - pytorch
 - nvidia
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested pytorch-cuda 12.1**
  - nothing provides __win needed by cuda-12.1.1-h7428d3b_0

Could not solve for environment specs
The following packages are incompatible
├─ cuda 12.1**  is not installable because there are no viable options
│  ├─ cuda 12.1.1 would require
│  │  └─ __win, which is missing on the system;
│  └─ cuda 12.1.1 would require
│     └─ __linux, which is missing on the system;
└─ pytorch-cuda 12.1**  does not exist (perhaps a typo or a missing channel).

**Comment by paulengstler** [comment]
In theory, I believe this project should run on a Mac using the CPU if all CUDA requirements are removed and the code is appropriately adapted, such that the point cloud generated with PyTorch3D is exported as opposed to Gaussians. That likely requires changes to at least `environment.yml`, `requirements.txt`, and `run.py`. While I'm unsure if I can provide these changes myself, I'd be happy to consider a pull request!
