### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by ryansburgoyne** [paulengstler/invisible-stitch#7]
I'm getting an error `torch.cuda.OutOfMemoryError: CUDA out of memory.`. I am using a GeForce RTX 4070 Ti which has 12 GB of memory. Is that too little for this project? If so, what GPU configuration is recommended?

**Comment by ryansburgoyne** [comment]
I switched to a cloud server with an A40 which as 48GB VRAM and no longer got this error. However 16GB system RAM was not enough for 360 mode. I had to up it to 32GB.

**Comment by paulengstler** [comment]
Thanks for making a note of this! In my experiments, a gpu with 16GB VRAM was sufficient. I've updated the README.
