### ISSUE TITLE
UnboundLocalError: local variable 'azim_steps' referenced before assignment

### ISSUE THREAD

**Issue by ryansburgoyne** [paulengstler/invisible-stitch#8]
When I use `--mode "360"`, I get `UnboundLocalError: local variable 'azim_steps' referenced before assignment`. It looks like the `mode` variable is an integer in that case and so it doesn't match `elif mode == "360"`. Changing that to `elif mode == 360` got past the error, but there is probably a nicer fix.

**Comment by paulengstler** [comment]
Thanks! I'm surprised I didn't see this behavior of `fire` in my experiments. Either way, it's fixed with 8156c79.
