### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by ryansburgoyne** [paulengstler/invisible-stitch#9]
What is the license for the provided code?

It would be great to see a permissive license like MIT. One concern in that regard is the use of https://github.com/graphdeco-inria/diff-gaussian-rasterization/, and simple-knn which are not licensed for commercial use. Would it be possible to use https://github.com/nerfstudio-project/gsplat instead?

**Comment by paulengstler** [comment]
In accordance with my university's [Open Access](https://openaccess.ox.ac.uk/oapp) policy, the code for this project is BSD-licensed. I've thought about adopting gsplat but I cannot give a timeline for that. Exporting the point cloud itself before it goes into the Gaussian splatting optimization process is also possible. I hope this helps!

**Comment by paulengstler** [comment]
I was able to find some time to update the Gaussian optimization code. With the new version, the only related requirement going forward is gsplat. Cheers!

**Comment by ryansburgoyne** [comment]
Awesome, thanks for doing that!
